import { Config, Stats } from "@/types";

export const defaultConfig: Config = {
    default_max_downvotes: 5,
    proposal_escrow_amount_xdr: 0,
    staging: "",
    staging2: "",
    weekly_auction_size_tokens: 0,
    user_report_validity_days: 0,
    downvote_counting_period_days: 0,
    max_report_length: 0,
    credits_per_xdr: 0,
    max_funding_amount: 0,
    min_stalwart_karma: 0,
    min_credits_for_inviting: 0,
    max_credits_mint_kilos: 0,
    logo: "",
    poll_revote_deadline_hours: 0,
    account_activation_cost: 0,
    blob_cost: 0,
    poll_cost: 0,
    max_post_length: 0,
    max_blob_size_bytes: 0,
    identity_change_cost: 0,
    max_realm_name: 24,
    max_realm_logo_len: 0,
    post_cost: 0,
    post_deletion_penalty_factor: 0,
    token_symbol: "TAGGR",
    transaction_fee: 0,
    maximum_supply: 0,
    proposal_approval_threshold: 0,
    name: "TAGGR",
    proposal_rejection_penalty: 0,
    voting_power_activity_weeks: 0,
    trusted_user_min_karma: 0,
    trusted_user_min_age_weeks: 0,
    min_stalwart_account_age_weeks: 0,
    min_stalwart_activity_weeks: 0,
    feed_page_size: 20,
    reactions: [],
    token_decimals: 8,
    reporting_penalty_misbehaviour: 0,
};

export const defaultStats: Stats = {
    realms: 0,
    fees_burned: 0,
    volume_day: 0,
    volume_week: 0,
    users: 0,
    active_users: 0,
    active_users_vp: 0,
    users_online: 0,
    credits: 0,
    burned_credits: BigInt(0),
    circulating_supply: 0,
    total_rewards_shared: BigInt(0),
    total_revenue_shared: BigInt(0),
    canister_cycle_balance: BigInt(0),
    last_release: {
        post_id: 0,
        timestamp: 0,
        commit: "",
    },
    bots: [],
    weekly_karma_leaders: [],
    invited_users: 0,
    posts: 0,
    comments: 0,
    bootcamp_users: 0,
    state_size: 0,
    account: "",
    last_weekly_chores: BigInt(0),
    e8s_for_one_xdr: BigInt(0),
    e8s_revenue_per_1k: BigInt(0),
    canister_id: "",
    vesting_tokens_of_x: [0, 0],
    buckets: [],
    stalwarts: [],
};
